include:
  - project: sequence/templates/cicd
    file: .gitlab-ci.linux.yml

variables:
  PACKAGE_NAME_NUGET: Sequence.Core
  PACKAGE_NAME_DLL: Sequence.Core
  PUBLISH_NUGETORG: 1

stages:
  - antlr
  - build
  - test
  - quality
  - package
  - sign
  - push

compile grammar:
  stage: antlr
  image: openjdk:11-jre-buster
  variables:
    ANTLR_JAR_URI: https://www.antlr.org/download/antlr-4.11.1-complete.jar
    ANTLR_JAR: antlr-4.11.1-complete.jar
    ANTLR_ENCODING: UTF-8
    ANTLR_NAMESPACE: Sequence.Core.Internal.Parser
    ANTLR_OUTPUT: ./Core/Antlr
    ANTLR_GRAMMAR: ./Core/Internal/Parser/SCL.g4
  script:
    - wget -O $ANTLR_JAR $ANTLR_JAR_URI
    - java -jar $ANTLR_JAR -Dlanguage=CSharp -visitor -no-listener -Werror
      -encoding $ANTLR_ENCODING -package $ANTLR_NAMESPACE -o $ANTLR_OUTPUT
      -Xexact-output-dir $ANTLR_GRAMMAR
  artifacts:
    paths:
      - $ANTLR_OUTPUT
    expire_in: 2 hours

test dev:
  script:
    - dotnet test --no-build --configuration $CONFIG --collect:"XPlat Code Coverage" --results-directory ./
      --settings coverlet.runsettings

mutation testing:
  needs:
    - compile grammar
  rules:
    - when: never
